//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorTask
    {
        public int MonitorTask_ID { get; set; }
        public int Monitor_ID { get; set; }
        public int Task_ID { get; set; }
    
        public virtual Monitor Monitor { get; set; }
        public virtual Task Task { get; set; }
    }
}
